[workspace]
members = ["rekcod-core", "rekcod-server", "rekcod-agent", "rekcod"]
resolver = "2"


[workspace.dependencies]
tokio = "1"
clap = "4"
axum = "0.7"
anyhow = "1"
hyperlocal = "0.9"
bollard = "0.17"
hyper-util = "0.1"
hyper = "1"
hyper-named-pipe = "0.1"
http = "0.2"
async-trait = "0.1"
