
@host = localhost
@port = 6734


### get node list
POST http://{{host}}:{{port}}/api/node/list
Content-Type: application/json

{}

### deploy
POST http://{{host}}:{{port}}/api/app/deploy
Content-Type: application/json

{
    "name": "test2",
    "app_name": "test2",
    "node_name": "172.17.0.5",
    "build": true
}